### ISSUE TITLE
#12 Setup Heroku Pipeline

### ISSUE THREAD

**Issue by azuryue** [Crysicia/THPNext-ECommerce#17]
- Non regression checklist :
Until integration tests are automated for this app, they should be done manually on the staging environment. This means that each time an issue is over, the corresponding branch is merged on master and automatically deployed on the staging. The developer in charge of the issue should visit the staging app and follow the steps of the non-regression check-list A non regression checklist is a list of actions to execute manually on the site in order to check that the application still behaves the way it should after a modification of code has been made. "Non regression", refers to the fact that things that were working in a given way before the new code was pushed, should work the same war after the new code is pushed. Don't forget to update your non-regression checklist as the features of your app grow and change.

- Staging :
Setup automatic deploys from your master branch to your staging environment.
Non regression and manual integration tests.

**Comment by Crysicia** [comment]
Done 🐙

**Comment by azuryue** [comment]
@Crysicia demain faudra que tu nous mette collaborateur. Tarek voudrait check notre app en prod.

**Comment by Crysicia** [comment]
C'est déjà fait, baka :p
