### ISSUE TITLE
Create tables

### ISSUE THREAD

**Issue by MelloFlo** [Crysicia/THPNext-ECommerce#4]
- Item
- Category
- Wishlist
- Profile
- Comments

**Comment by azuryue** [comment]
Déjà fait avant le point Zoom de vendredi 25 janvier (fin S3).
Non MVP & non agile, mais on garde les tables et ce qui a déjà été fait.
@MelloFlo peux-tu faire PR et me mettre en reviewer pour que je close l'issue stp ?
